locals {
  ictsc7_members = [
    "kyontan",
    "suzutan",
    "h-otter",
    "guragusan",
    "palloc",
    "yuukinetwork",
    "oomorio",
    "kadokusei",
    "naoki912",
    "yaminoma",
    "bosan120",
    "if001",
    "matsurika1226",
    "inuyosi",
    "Kurorororo",
    "alisamon",
    "yatuhashi",
    "alias-aria",
    "Katsuya414",
    "ecodrive-18",
    "mbook-x86",
  ]
}
