locals {
  ictsc2018_members = [
    "h-otter",
    "palloc",
    "Kurorororo",
    "yatuhashi",
    "icchy",
    "whywaita",
    "gurapomu",
    "acque2two",
    "yukamoja",
    "ha-kun0711",
    "uplus",
    "sharknasuhorse",
    "shinonome01",
    "kyontan",
    "takehaya",
    "proelbtn",
    "orin24",
    "bosan120",
    "ShotaKitazawa",
    "potyama",
    "NozomiSugiyama",
    "onokatio",
  ]
}
