locals {
  ictsc6_members = [
    "ibucho",
    "netmarkjp",
    "y-monma",
    "kurochan",
    "h-otter",
    "int-tt",
    "yuukinetwork",
    "a-r-g-v",
    "kyontan",
    "chalkygames123",
    "suzutan",
    "guragusan",
    "miyao11",
    "aoi96",
    "kyoko0514",
    "palloc",
    "yo-taro",
    "asdfec",
    "notchi590",
    "kamijin-fanta",
    "asarijiru",
    "tar-xzvff",
  ]
}
