locals {
  ictsc8_members = [
    "kyontan",
    "h-otter",
    "palloc",
    "oomorio",
    "naoki912",
    "bosan120",
    "if001",
    "inuyosi",
    "Kurorororo",
    "alisamon",
    "yatuhashi",
    "alias-aria",
    "Katsuya414",
    "ecodrive-18",
    "mbook-x86",
    "aoi96",
    "icchy",
    "staybuzz",
    "whywaita",
    "chisaton1",
    "Azusa72",
    "keyakko",
  ]
}