locals {
  ictsc9_members = [
    "h-otter",
    "palloc",
    "naoki912",
    "Kurorororo",
    "alisamon",
    "yatuhashi",
    "ecodrive-18",
    "mbook-x86",
    "icchy",
    "whywaita",
    "chisaton1",
    "gurapomu",
    "SakurazakaShin",
    "acque2two",
    "yukamoja",
    "ha-kun0711",
    "uplus",
    "sharknasuhorse",
    "tsuttsu305",
    "nomeaning777",
    "shinonome01",
    "itakuya",
    "freedom18",
  ]
}
