locals {
  ictsc2020_members = [
    "yukamoja",
    "uplus",
    "takehaya",
    "proelbtn",
    "potyama",
    "onokatio",
    "Terfno",
    "TenkiGit",
    "kapibara824",
    "arupakan125",
    "yoneyan",
    "site0801",
    "yo-kanyukari",
    "ophum",
    "hibiki31",
    "rlia",
    "nakasyo2650",
    "naoki2001",
    "928k1110",
    "Hicky1025",
    "zeroalphat",
    "tanishi001",
    "x86taka",
  ]
}