locals {
  admin_members = [
    "kurochan",
    "netmarkjp",
    "ibucho",
    "whywaita",
    "tar-xzvff",
    "h-otter",
    "sharknasuhorse",
    "uplus",
    "yukamoja",
    "takehaya",
    "proelbtn",
    "onokatio",
    "Explosive6363",
    "x86taka",
    "nishinoyama",
    "Crow314",
    "logica0419",
    "mu-ruU1",
    "tosuke",
    "Dodai-Dodai",
    "private-yusuke",
    "Fuuma0000",
  ]
}
